/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhnguyen
 */
public class ReportingJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form ReportingJPanel
     */
    public ReportingJPanel(JPanel userProcessContainer, EcoSystem system) {
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        initComponents();
        showReport((String) cmbReport.getSelectedItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReport = new javax.swing.JLabel();
        cmbReport = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        lblTitle1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnViewReport = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(731, 460));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReport.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblReport.setText("Report:");
        add(lblReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, 30));

        cmbReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "System Summary", "Work Requests by Status", "Work Requests by Enterprise", "Top Requesters" }));
        cmbReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbReportActionPerformed(evt);
            }
        });
        add(cmbReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 470, 30));

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Metric", "Count"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReport);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 580, 250));

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        lblTitle1.setText("Performance Reports");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, 30));

        btnViewReport.setBackground(new java.awt.Color(0, 102, 204));
        btnViewReport.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnViewReport.setForeground(new java.awt.Color(255, 255, 255));
        btnViewReport.setText("View Report");
        btnViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportActionPerformed(evt);
            }
        });
        add(btnViewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        if (component instanceof SystemAdminWorkAreaJPanel) {
            ((SystemAdminWorkAreaJPanel) component).populateTree();
        }
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportActionPerformed
        showReport((String) cmbReport.getSelectedItem());
    }//GEN-LAST:event_btnViewReportActionPerformed

    private void cmbReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewReport;
    private javax.swing.JComboBox<String> cmbReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables

    private void showReport(String reportName) {
        if (reportName.equals("System Summary")) {
            loadSystemSummaryReport();
        } else if (reportName.equals("Work Requests by Status")) {
            loadWorkRequestsByStatusReport();
        } else if (reportName.equals("By Enterprise")) {
            loadByEnterpriseReport();
        } else if (reportName.equals("Top Requesters")) {
            loadTopRequestersReport();
        }
    }

    // Walks the whole EcoSystem once, counting everything at the system/network level
    private void loadSystemSummaryReport() {
        int networkCount = system.getNetworkList().size();
        int enterpriseCount = 0;
        int organizationCount = 0;
        int employeeCount = 0;
        int accountCount = 0;
        int requestCount = 0;

        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                enterpriseCount++;
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    organizationCount++;
                    employeeCount += organization.getEmployeeDirectory().getEmployeeList().size();
                    accountCount += organization.getUserAccountDirectory().getUserAccountList().size();
                    requestCount += organization.getWorkQueue().getWorkRequestList().size();
                }
            }
        }

        String[] columns = {"Metric", "Count"};
        Object[][] data = {
            {"Networks", networkCount},
            {"Enterprises", enterpriseCount},
            {"Organizations", organizationCount},
            {"Employees", employeeCount},
            {"User Accounts", accountCount},
            {"Work Requests", requestCount}
        };
        tblReport.setModel(new DefaultTableModel(data, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    private void loadWorkRequestsByStatusReport() {
        Map<String, Integer> statusCounts = new HashMap<>();

        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
                        String status = request.getStatus() == null ? "(no status)" : request.getStatus();
                        int current = statusCounts.getOrDefault(status, 0);
                        statusCounts.put(status, current + 1);
                    }
                }
            }
        }

        String[] columns = {"Status", "Count"};
        Object[][] data = new Object[statusCounts.size()][2];
        int i = 0;
        for (Map.Entry<String, Integer> entry : statusCounts.entrySet()) {
            data[i][0] = entry.getKey();
            data[i][1] = entry.getValue();
            i++;
        }
        tblReport.setModel(new DefaultTableModel(data, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    private void loadByEnterpriseReport() {
        String[] columns = {"Enterprise", "Type", "Organizations", "Employees", "Accounts", "Work Requests"};
        java.util.ArrayList<Object[]> rows = new java.util.ArrayList<>();

        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                int orgCount = enterprise.getOrganizationDirectory().getOrganizationList().size();
                int employeeCount = 0;
                int accountCount = 0;
                int requestCount = 0;
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    employeeCount += organization.getEmployeeDirectory().getEmployeeList().size();
                    accountCount += organization.getUserAccountDirectory().getUserAccountList().size();
                    requestCount += organization.getWorkQueue().getWorkRequestList().size();
                }
                rows.add(new Object[]{
                    enterprise.getName(),
                    enterprise.getEnterpriseType().getValue(),
                    orgCount, employeeCount, accountCount, requestCount
                });
            }
        }

        Object[][] data = rows.toArray(new Object[0][]);
        tblReport.setModel(new DefaultTableModel(data, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    // Counts how many work requests each user sent, sorted highest first
    private void loadTopRequestersReport() {
        Map<String, Integer> requesterCounts = new HashMap<>();

        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
                        if (request.getSender() == null) {
                            continue;
                        }
                        String username = request.getSender().getUsername();
                        int current = requesterCounts.getOrDefault(username, 0);
                        requesterCounts.put(username, current + 1);
                    }
                }
            }
        }

        String[] columns = {"Requester", "Requests Sent"};
        Object[][] data = new Object[requesterCounts.size()][2];
        int i = 0;
        for (Map.Entry<String, Integer> entry : requesterCounts.entrySet()) {
            data[i][0] = entry.getKey();
            data[i][1] = entry.getValue();
            i++;
        }

        // Simple selection sort - put the highest count first
        for (int a = 0; a < data.length; a++) {
            int maxIndex = a;
            for (int b = a + 1; b < data.length; b++) {
                int countB = (Integer) data[b][1];
                int countMax = (Integer) data[maxIndex][1];
                if (countB > countMax) {
                    maxIndex = b;
                }
            }
            Object[] temp = data[a];
            data[a] = data[maxIndex];
            data[maxIndex] = temp;
        }

        tblReport.setModel(new DefaultTableModel(data, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }
}
