/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.OperationsManagerRole;

import Business.WorkQueue.PriorityRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author anhnguyen
 */
public class ProcessPriorityRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PriorityRequest request;

    /**
     * Creates new form ProcessPriorityRequestJPanel
     */
    public ProcessPriorityRequestJPanel(JPanel userProcessContainer, PriorityRequest request) {
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        cmbPriorityLevel = new javax.swing.JComboBox<>();
        txtETA = new javax.swing.JTextField();
        lblPriorityLevel = new javax.swing.JLabel();
        lblETA = new javax.swing.JLabel();
        btnReject = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lblTitle.setText("Process Priority Request");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnApprove.setBackground(new java.awt.Color(0, 102, 204));
        btnApprove.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(255, 255, 255));
        btnApprove.setText("Approve & Complete");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        cmbPriorityLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cmbPriorityLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPriorityLevelActionPerformed(evt);
            }
        });
        add(cmbPriorityLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 290, 40));
        add(txtETA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 290, 40));

        lblPriorityLevel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPriorityLevel.setText("Priority Level (1 = highest, 5 = lowest):");
        add(lblPriorityLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        lblETA.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblETA.setText("Estimated Completion Date: ");
        add(lblETA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        btnReject.setBackground(new java.awt.Color(204, 0, 51));
        btnReject.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnReject.setForeground(new java.awt.Color(255, 255, 255));
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        if (component instanceof ManufacturerOperationsManagerWorkArea) {
            ((ManufacturerOperationsManagerWorkArea) component).populateTable();
        }
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        if (txtETA.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Estimated completion date is required.");
            return;
        }
        int priorityLevel = Integer.parseInt((String) cmbPriorityLevel.getSelectedItem());
        request.setPriorityLevel(priorityLevel);
        request.setEstimatedCompletionDate(txtETA.getText().trim());
        request.setApproved(true);
        request.setStatus("Completed");
        JOptionPane.showMessageDialog(this, "Priority request updated.");
        btnBackActionPerformed(evt);
    }//GEN-LAST:event_btnApproveActionPerformed

    private void cmbPriorityLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPriorityLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPriorityLevelActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        request.setApproved(false);
        request.setStatus("Rejected");
        JOptionPane.showMessageDialog(this, "Priority request rejected.");
        btnBackActionPerformed(evt);
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JComboBox<String> cmbPriorityLevel;
    private javax.swing.JLabel lblETA;
    private javax.swing.JLabel lblPriorityLevel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtETA;
    // End of variables declaration//GEN-END:variables

}
