/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.WholesalerSales;

import ui.WholesalerPricing.WholesalerPricingToManufacturer;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Kenneth Garcia
 */
public class WholesalerSalesMenuJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;

    public WholesalerSalesMenuJPanel() {
        this(null, null, null, null);
    }

    public WholesalerSalesMenuJPanel(JPanel userProcessContainer,UserAccount account,Organization organization,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDataRequestManufacturer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalesData = new javax.swing.JButton();
        btnDataRequestPricing = new javax.swing.JButton();
        btnSellProducts = new javax.swing.JButton();

        btnDataRequestManufacturer.setBackground(new java.awt.Color(102, 153, 255));
        btnDataRequestManufacturer.setForeground(new java.awt.Color(255, 255, 255));
        btnDataRequestManufacturer.setText("Make Marketing Request");
        btnDataRequestManufacturer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDataRequestManufacturer.setMaximumSize(new java.awt.Dimension(145, 40));
        btnDataRequestManufacturer.setMinimumSize(new java.awt.Dimension(20, 20));
        btnDataRequestManufacturer.setPreferredSize(new java.awt.Dimension(240, 25));
        btnDataRequestManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataRequestManufacturerIdentifyEventsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Sales Menu");

        btnSalesData.setBackground(new java.awt.Color(102, 153, 255));
        btnSalesData.setForeground(new java.awt.Color(255, 255, 255));
        btnSalesData.setText("View Sales Data ");
        btnSalesData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalesData.setMaximumSize(new java.awt.Dimension(200, 40));
        btnSalesData.setMinimumSize(new java.awt.Dimension(20, 23));
        btnSalesData.setPreferredSize(new java.awt.Dimension(240, 30));
        btnSalesData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesDataIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnDataRequestPricing.setBackground(new java.awt.Color(102, 153, 255));
        btnDataRequestPricing.setForeground(new java.awt.Color(255, 255, 255));
        btnDataRequestPricing.setText("Request Pricing Change");
        btnDataRequestPricing.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDataRequestPricing.setMaximumSize(new java.awt.Dimension(200, 40));
        btnDataRequestPricing.setMinimumSize(new java.awt.Dimension(20, 20));
        btnDataRequestPricing.setPreferredSize(new java.awt.Dimension(240, 25));
        btnDataRequestPricing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataRequestPricingActionPerformed(evt);
            }
        });

        btnSellProducts.setBackground(new java.awt.Color(102, 153, 255));
        btnSellProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnSellProducts.setText("Order Processing");
        btnSellProducts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSellProducts.setMaximumSize(new java.awt.Dimension(200, 40));
        btnSellProducts.setMinimumSize(new java.awt.Dimension(20, 23));
        btnSellProducts.setPreferredSize(new java.awt.Dimension(240, 30));
        btnSellProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellProductsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalesData, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDataRequestManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDataRequestPricing, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(btnSellProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalesData, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDataRequestPricing, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDataRequestManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSellProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataRequestManufacturerIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataRequestManufacturerIdentifyEventsActionPerformed
        // TODO add your handling code here:
        if (userProcessContainer == null) {
            return;
        }
        Enterprise targetEnterprise = business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().stream().filter(e -> e.getName().equals("Nike")).findFirst().orElse(null);
        for (Organization org : targetEnterprise.getOrganizationDirectory().getOrganizationList()) {
            System.out.println("Checking org: " + org.getName()); // DEBUG

            if (org.getName().equalsIgnoreCase("Supplier Marketing Organization")) {
                Organization targetOrg = org;
                // Go to the panel that lets analyst make manufacturer & pricing requests
                WholesalerMarketingRequestJPanel panel
                        = new WholesalerMarketingRequestJPanel(
                                userProcessContainer,
                                userAccount,
                                targetOrg,
                                business
                        );

                userProcessContainer.add("WholesalerMarketingRequestJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
    }//GEN-LAST:event_btnDataRequestManufacturerIdentifyEventsActionPerformed

    private void btnSalesDataIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesDataIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        Enterprise targetEnterprise = business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().stream().filter(e -> e.getName().equals("Nike")).findFirst().orElse(null);
        for (Organization org : targetEnterprise.getOrganizationDirectory().getOrganizationList()) {
            System.out.println("Checking org: " + org.getName()); // DEBUG

            if (org.getName().equalsIgnoreCase("Wholesaler Sales Organization")) {
                Organization targetOrg = org;
                WholesalerSalesOrdersJPanel wholesalerSalesInventoryJPanel
                        = new WholesalerSalesOrdersJPanel(userProcessContainer,userAccount,org,business,targetEnterprise);

                userProcessContainer.add(
                        "WholesalerSalesInventoryJPanel",
                        wholesalerSalesInventoryJPanel
                );

                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
    }//GEN-LAST:event_btnSalesDataIdentifyResourceAssetsActionPerformed

    private void btnDataRequestPricingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataRequestPricingActionPerformed
        // TODO add your handling code here:
        if (userProcessContainer == null) {
            return;
        }
        Enterprise targetEnterprise = business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().stream().filter(e -> e.getName().equals("Nike")).findFirst().orElse(null);
        for (Organization org : targetEnterprise.getOrganizationDirectory().getOrganizationList()) {
            System.out.println("Checking org: " + org.getName()); // DEBUG

            if (org.getName().equalsIgnoreCase("Wholesaler Pricing Organization")) {
                Organization targetOrg = org;
                WholesalerSalesPricingRequestJPanel wholesalerSalesPricingRequestJPanel
                        = new WholesalerSalesPricingRequestJPanel(userProcessContainer,userAccount,targetOrg,business);

                userProcessContainer.add("WholesalerPricingRequestJPanel", wholesalerSalesPricingRequestJPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);

            }
        }
    }//GEN-LAST:event_btnDataRequestPricingActionPerformed

    private void btnSellProductsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellProductsIdentifyResourceAssetsActionPerformed
        if (userProcessContainer == null) {
            return;
        }

        // Same work area also shows inventory; you can reuse it
        SellWholesalerProductsJPanel sellWholesalerProductsJPanel =
        new SellWholesalerProductsJPanel(
            userProcessContainer,
            business
        );

        userProcessContainer.add("SellWholesalerProductsJPanel", sellWholesalerProductsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.show(userProcessContainer,"SellWholesalerProductsJPanel");

    }//GEN-LAST:event_btnSellProductsIdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataRequestManufacturer;
    private javax.swing.JButton btnDataRequestPricing;
    private javax.swing.JButton btnSalesData;
    private javax.swing.JButton btnSellProducts;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
