/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProductionAnalystRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.QuoteRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhnguyen
 */
public class ProductionAnalystMenuJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private EcoSystem business;
    private Enterprise enterprise;

    private JTable requestTable;

    /**
     * Creates new form ProductionAnalystMenuJPanel
     */
    public ProductionAnalystMenuJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise) {
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.business = business;
        this.enterprise = enterprise;

        initComponents();
        lblEnterprise.setText("Enterprise: " + enterprise.getName());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequests = new javax.swing.JTable();
        btnResponse = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        btnSubmitPriority = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblWorkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type", "Message", "Status", "With"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 650, 220));

        btnResponse.setBackground(new java.awt.Color(0, 102, 204));
        btnResponse.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnResponse.setForeground(new java.awt.Color(255, 255, 255));
        btnResponse.setText("Respond to Quote Request");
        btnResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponseActionPerformed(evt);
            }
        });
        add(btnResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        btnRefresh.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lblTitle1.setText("Production Analyst Menu");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btnSubmitPriority.setBackground(new java.awt.Color(0, 102, 204));
        btnSubmitPriority.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSubmitPriority.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitPriority.setText("Submit Priority Request");
        btnSubmitPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPriorityActionPerformed(evt);
            }
        });
        add(btnSubmitPriority, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblEnterprise.setText("Enterprise:");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 360, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponseActionPerformed
        int row = tblWorkRequests.getSelectedRow();
        WorkRequest selected = getRowRequest(row);
        if (!(selected instanceof QuoteRequest)) {
            JOptionPane.showMessageDialog(this, "Select a quote request from the list first.");
            return;
        }
        RespondQuoteRequestJPanel panel = new RespondQuoteRequestJPanel(userProcessContainer, (QuoteRequest) selected);
        userProcessContainer.add("RespondQuoteRequestJPanel", panel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);

    }//GEN-LAST:event_btnResponseActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSubmitPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPriorityActionPerformed
        // TODO add your handling code here:
        SubmitPriorityRequestJPanel panel = new SubmitPriorityRequestJPanel(userProcessContainer, account, organization);
        userProcessContainer.add("SubmitPriorityRequestJPanel", panel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);

    }//GEN-LAST:event_btnSubmitPriorityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnResponse;
    private javax.swing.JButton btnSubmitPriority;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTable tblWorkRequests;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) requestTable.getModel();
        model.setRowCount(0);

        // Outgoing priority requests (from this account's own queue)
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
            model.addRow(rowFor(request));
        }
        // Incoming quote requests (sitting in the organization's queue, not yet in this account's queue)
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof Business.WorkQueue.QuoteRequest && !account.getWorkQueue().getWorkRequestList().contains(request)) {
                model.addRow(rowFor(request));
            }
        }
    }

    private Object[] rowFor(WorkRequest request) {
        Object[] row = new Object[4];
        row[0] = request.getClass().getSimpleName();
        row[1] = request.getMessage();
        row[2] = request.getStatus();
        row[3] = request.getSender() == account
                ? (request.getReceiver() == null ? "(unassigned)" : request.getReceiver().getUsername())
                : (request.getSender() == null ? "(unknown)" : request.getSender().getUsername());
        return row;
    }

    private WorkRequest getRowRequest(int row) {
        if (row < 0) {
            return null;
        }
        int i = 0;
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
            if (i == row) {
                return request;
            }
            i++;
        }
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof QuoteRequest && !account.getWorkQueue().getWorkRequestList().contains(request)) {
                if (i == row) {
                    return request;
                }
                i++;
            }
        }
        return null;
    }

}
