/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProductionAnalystRole;

import Business.WorkQueue.QuoteRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anhnguyen
 */
public class RespondQuoteRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private QuoteRequest request;

    /**
     * Creates new form RespondQuoteRequestJPanel
     */
    public RespondQuoteRequestJPanel(JPanel userProcessContainer, QuoteRequest request) {
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        initComponents();
        lblItemValue.setText(request.getItemName());
        lblQuantityValue.setText(String.valueOf(request.getQuantity()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblQPrice = new javax.swing.JLabel();
        lblItem = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        txtQPrice = new javax.swing.JTextField();
        lblItemValue = new javax.swing.JLabel();
        lblQuantityValue = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lblTitle.setText("Respond to Quote Request");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblQPrice.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblQPrice.setText("Quoted price ($):");
        add(lblQPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 20));

        lblItem.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblItem.setText("Item:");
        add(lblItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 20));

        lblQuantity.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblQuantity.setText("Quantity:");
        add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        txtQPrice.setForeground(new java.awt.Color(102, 102, 102));
        add(txtQPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 150, 30));

        lblItemValue.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        add(lblItemValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 150, 30));

        lblQuantityValue.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        add(lblQuantityValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 150, 30));

        btnSubmit.setBackground(new java.awt.Color(0, 102, 204));
        btnSubmit.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit Quote");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 150, 30));

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("e.g. 4500.00");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        double price;
        try {
            price = Double.parseDouble(txtQPrice.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Enter a valid price.");
            return;
        }

        request.setQuotedPrice(price);
        request.setApproved(true);
        request.setStatus("Completed");

        JOptionPane.showMessageDialog(this, "Quote submitted.");
        btnBackActionPerformed(evt);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        if (component instanceof ProductionAnalystMenuJPanel) {
            ((ProductionAnalystMenuJPanel) component).populateTable();
        }
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblItemValue;
    private javax.swing.JLabel lblQPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblQuantityValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtQPrice;
    // End of variables declaration//GEN-END:variables
}
