/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProductionAnalystRole;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PriorityRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anhnguyen
 */
public class SubmitPriorityRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;

    /**
     * Creates new form SubmitPriorityRequestJPanel
     */
    public SubmitPriorityRequestJPanel(JPanel userProcessContainer, UserAccount account, Organization organization) {
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblItem = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        btnSubmitRequest = new javax.swing.JButton();
        txtMessage = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lblTitle.setText("Submit Priority Request");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblItem.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblItem.setText("Item/ Order Name:");
        add(lblItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        lblMessage.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblMessage.setText("Message:");
        add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        txtItem.setForeground(new java.awt.Color(102, 102, 102));
        add(txtItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 470, 40));

        btnSubmitRequest.setBackground(new java.awt.Color(0, 102, 204));
        btnSubmitRequest.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSubmitRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitRequest.setText("Submit Priority Request");
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });
        add(btnSubmitRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 200, 30));

        txtMessage.setForeground(new java.awt.Color(102, 102, 102));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 470, 40));

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("e.g. Need 500 units by Q3");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, -1));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("e.g. Steel Frame");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        // TODO add your handling code here:
        String itemName = txtItem.getText().trim();
        String message = txtMessage.getText().trim();

        if (itemName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Item name is required.");
            return;
        }

        PriorityRequest request = new PriorityRequest();
        request.setItemName(itemName);
        request.setMessage(message);
        request.setSender(account);
        request.setStatus("Sent");

        organization.getWorkQueue().getWorkRequestList().add(request);
        account.getWorkQueue().getWorkRequestList().add(request);

        JOptionPane.showMessageDialog(this, "Priority request submitted.");
        btnBackActionPerformed(evt);
    }//GEN-LAST:event_btnSubmitRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        if (component instanceof ProductionAnalystMenuJPanel) {
            ((ProductionAnalystMenuJPanel) component).populateTable();
        }
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
